[package]
name = "xelis-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
xelis-bytecode = { path = "../bytecode" }
xelis-types = { path = "../types" }
xelis-environment = { path = "../environment" }
thiserror = "2.0.3"

[dev-dependencies]
xelis-builder = { path = "../builder" }
xelis-lexer ={ path = "../lexer" }
xelis-parser = { path = "../parser" }
xelis-compiler = { path = "../compiler" }
criterion = "0.5.1"

[[bench]]
name = "vm"
harness = false
