[package]
name = "xelis-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
xelis-types = { path = "../types" }
xelis-ast = { path = "../ast" }
xelis-environment = { path = "../environment" }
thiserror = "2.0.1"
paste = "1.0.15"
